### PR TITLE
fix: number filter mapping bug

### LINKED ISSUE #37: Bug: Number filters are dropped due to incorrect operation mapping in getFilterModel
## Discovery
This bug was discovered while creating a PoC for #34 during comprehensive multi-type filter testing that revealed number filters weren't working as expected. The issue has likely existed since number filter support was first introduced.

## Description

Number filters applied in AG Grid are being dropped when parsed by `getFilterModel()` due to incorrect operation mapping. The current implementation incorrectly uses `REVERSE_AG_GRID_OPERATION_NAMES` for number filters, which maps AG Grid's generic operation names (like `"greaterThan"`) to date-specific internal operations (like `"dateAfter"`).

## Steps to Reproduce

1. Apply a number filter in AG Grid (e.g., "age > 25")
2. Call `getFilterModel()` or try to generate a URL with the filter
3. The number filter is silently dropped from the result

## Expected Behavior

Number filters should be correctly parsed and included in the filter state, allowing them to be:
- Serialized to URL parameters
- Applied back to the grid
- Used in grouped serialization

## Actual Behavior

Number filters are dropped because:
1. AG Grid returns `{ filterType: 'number', type: 'greaterThan', filter: 25 }`
2. `REVERSE_AG_GRID_OPERATION_NAMES["greaterThan"]` returns `"dateAfter"`
3. `isNumberFilterOperation("dateAfter")` returns `false`
4. The filter is skipped and not included in the result

## Root Cause

The `REVERSE_AG_GRID_OPERATION_NAMES` mapping was designed for date operations and incorrectly maps generic AG Grid operations to date-specific internal operations:

```typescript
// Current problematic code
const internalOperation = REVERSE_AG_GRID_OPERATION_NAMES[type] // "greaterThan" -> "dateAfter"
if (internalOperation && isNumberFilterOperation(internalOperation)) { // false!
  // This block never executes for number filters
}

### PR DESCRIPTION
**Pull request by umxr**
closes #37

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
why did the lockfile change? also, no tests to check this behavior?

File: src/core/grid-integration.ts [hunk 1]
```diff
@@ -19,6 +19,20 @@ import {
...
+  lessThan: 'lessThan',
+  lessThanOrEqual: 'lessThanOrEqual',
+  greaterThan: 'greaterThan',
+  greaterThanOrEqual: 'greaterThanOrEqual',
+  inRange: 'inRange',
+  equals: 'eq',
+  notEqual: 'notEqual',
+  blank: 'blank',
+  notBlank: 'notBlank'
+} satisfies Record<string, FilterOperation>
```
Comment (Puppo) [inline src/core/grid-integration.ts]: You don't need the type, you can just use const and satisfies. I don't remember the order now, but double check with the editor
```suggestion
const AG_GRID_TO_NUMBER_OPERATION_MAP = {
  lessThan: 'lessThan',
  lessThanOrEqual: 'lessThanOrEqual',
  greaterThan: 'greaterThan',
  greaterThanOrEqual: 'greaterThanOrEqual',
  inRange: 'inRange',
  equals: 'eq',
  notEqual: 'notEqual',
  blank: 'blank',
  notBlank: 'notBlank'
} satisfies Record<string, FilterOperation> as const;
```

**Review by Puppo — COMMENTED** [review]
Small suggestion
